## Build all our Build Types at once ##
name: Build all artifacts
on: 
  pull_request:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: as sembleRelease
