name: Create Tag and Release APK on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 for building the Android app
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease

      # Create a zip file of the project source code
      - name: Zip project source code
        run: zip -r project-source.zip . -x "*.git*"

      # Find the name of the merged pull request (last commit message)
      - name: Get PR Title
        id: pr_title
        run: |
          PR_TITLE=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=title::$PR_TITLE"

      # Create a new tag with the PR title
      - name: Create Git Tag
        run: |
          TAG_NAME=${{ steps.pr_title.outputs.title }}
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Create GitHub release with the APK and code
      - name: Create Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.pr_title.outputs.title }}
          name: ${{ steps.pr_title.outputs.title }}
          body: "Release for PR: ${{ steps.pr_title.outputs.title }}"
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            project-source.zip
