name: Android Build Staging APK
on: 
  pull_request: 
    types:
      - opened
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
      - name: Get current branch
        run: >-
          echo ::set-output name=branch::<span class="math-inline">\(git rev\-parse
          \-\-abbrev\-ref HEAD\)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: false
          name: 'Release ${{ steps.branch.output }}'
          body: '${{ steps.changelog.outputs.releaseNotes }}'
          tag_name: '${{ steps.branch.output }}'
          files: app/build/outputs/apk/release/app-release.apk
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
          run: >
            curl -X POST -H 'Content-type: application/json' --data '{
    
            "text": "A new GitHub release has been created for branch \{\{
            steps\.branch\.output \}\}\. Download it here\: \'{{
            github.event.repository.html_url }}/releases/tag/${{ steps.branch.output
            }}'"
    
            }' $SLACK_WEBHOOK_URL
