name: Deploy to Alpha

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

#      - name: Tag Release
#        run: |
#          version_name=1
#          echo "Tagging release with tag $version_name"
#          git tag $version_name release/$version_name
#          git push origin --tags
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.abhishek.githubactions
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: distribution/
